FUNCTION fn_pi RETURNS DECIMAL (INPUT p-num AS INTEGER):
  
  RETURN (3.1415 * p-num).

END FUNCTION.

 MESSAGE fn_pi(10) 
    
    VIEW-AS ALERT-BOX QUESTION BUTTONS YES-NO UPDATE l-ok AS LOGICAL.
    
IF l-ok THEN DO:

    MESSAGE "Apertou OK" 
    VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
    
    MESSAGE "Continua"
    VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.

END.
  
  
    

    
